### ISSUE TITLE
>a action指令有误

### ISSUE THREAD

**Issue by hoxily** [Stevearzh/pyIRCbot#3]
“>a 动作”的处理遗漏了结尾的\x01。
连接：https://github.com/Stevearzh/pyIRCbot/blob/master/ircbot.py#L156
参考资料：http://www.irchelp.org/irchelp/rfc/ctcpspec.html 

> ![default](https://cloud.githubusercontent.com/assets/1575029/5971196/85658f30-a87b-11e4-8b4c-653b59810068.PNG)
> # ACTION
> 
> This is used by losers on IRC to simulate "role playing" games. An
> action message looks like the following:
> 
> \001ACTION barfs on the floor.\001

已知受影响的客户端：hexchat 2.10.2,andchat v1.4.3.2(Free)
已知未受影响的客户端：irssi（xeirrr所用版本）,weechat 1.0.1

**Comment by Stevearzh** [comment]
感谢反馈，bug 已修复。
